spring.application.name=journal_app
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journalDB
# spring.data.mongodb.username=if_username
# spring.data.mongodb.password=if_password
spring.data.mongodb.auto-index-creation=true